# Generated by Django 3.2.2 on 2021-10-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_category_name', models.CharField(max_length=250)),
                ('vchr_category_image', models.CharField(max_length=250)),
                ('vchr_delete_status', models.CharField(max_length=5)),
                ('vchr_last_modified_by', models.CharField(max_length=75)),
                ('vchr_last_modified_time', models.CharField(max_length=110)),
            ],
        ),
    ]
