# Generated by Django 3.2.2 on 2021-10-29 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xianpp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_branch_name', models.CharField(max_length=250)),
                ('vchr_branch_place', models.CharField(max_length=250)),
                ('vchr_branch_pincode', models.CharField(max_length=250)),
                ('vchr_branch_latitude', models.CharField(max_length=250)),
                ('vchr_branch_longitude', models.CharField(max_length=250)),
                ('vchr_branch_image', models.CharField(max_length=250)),
                ('text_branch_address', models.TextField()),
                ('int_is_branch_paid', models.BigIntegerField()),
                ('vchr_delete_status', models.CharField(max_length=5)),
                ('vchr_last_modified_by', models.CharField(max_length=75)),
                ('vchr_last_modified_time', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_salon_name', models.CharField(max_length=250)),
                ('vchr_salon_place', models.CharField(max_length=250)),
                ('vchr_salon_pincode', models.CharField(max_length=250)),
                ('vchr_salon_latitude', models.CharField(max_length=250)),
                ('vchr_salon_longitude', models.CharField(max_length=250)),
                ('vchr_salon_image', models.CharField(max_length=250)),
                ('text_salon_address', models.TextField()),
                ('int_salon_view_count', models.BigIntegerField()),
                ('int_is_salon_paid', models.BigIntegerField()),
                ('vchr_delete_status', models.CharField(max_length=5)),
                ('vchr_last_modified_by', models.CharField(max_length=75)),
                ('vchr_last_modified_time', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_name', models.CharField(max_length=250)),
                ('vchr_password', models.CharField(max_length=250)),
                ('vchr_email', models.CharField(max_length=250)),
                ('vchr_phone', models.CharField(max_length=250)),
                ('vchr_location', models.CharField(max_length=250)),
                ('enum_user_type', models.CharField(max_length=250)),
                ('vchr_delete_status', models.CharField(max_length=5)),
                ('vchr_last_modified_by', models.CharField(max_length=75)),
                ('vchr_last_modified_time', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_services_name', models.CharField(max_length=250)),
                ('vchr_services_price', models.CharField(max_length=250)),
                ('vchr_services_off_days', models.CharField(max_length=250)),
                ('vchr_services_spec_time', models.CharField(max_length=250)),
                ('vchr_services_duration', models.CharField(max_length=250)),
                ('vchr_services_speciality', models.CharField(max_length=250)),
                ('vchr_services_image', models.CharField(max_length=250)),
                ('text_services_desc', models.TextField()),
                ('text_services_special_instructions', models.TextField()),
                ('int_services_view_count', models.BigIntegerField()),
                ('int_services_status', models.BigIntegerField()),
                ('vchr_delete_status', models.CharField(max_length=5)),
                ('vchr_last_modified_by', models.CharField(max_length=75)),
                ('vchr_last_modified_time', models.CharField(max_length=110)),
                ('fk_int_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xianpp.tbl_branch')),
                ('fk_int_category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xianpp.tbl_category')),
                ('fk_int_salon_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xianpp.tbl_salon')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_salon',
            name='fk_int_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xianpp.tbl_user'),
        ),
        migrations.CreateModel(
            name='tbl_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_client_phone_alt', models.CharField(max_length=250)),
                ('vchr_client_email_alt', models.CharField(max_length=250)),
                ('vchr_client_image', models.CharField(max_length=250)),
                ('vchr_client_address', models.TextField()),
                ('enum_client_gender', models.CharField(max_length=250)),
                ('vchr_delete_status', models.CharField(max_length=5)),
                ('vchr_last_modified_by', models.CharField(max_length=110)),
                ('vchr_last_modified_time', models.CharField(max_length=75)),
                ('fk_int_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xianpp.tbl_user')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_branch',
            name='fk_int_salon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xianpp.tbl_salon'),
        ),
        migrations.AddField(
            model_name='tbl_branch',
            name='fk_int_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xianpp.tbl_user'),
        ),
    ]
